In [10]:
import pandas as pd
from sqlalchemy import create_engine
import numpy as np

In [27]:
csv_file = "Donald-Tweets.csv"
donald_data_df = pd.read_csv(csv_file)
donald_data_df

,Date,Time,Tweet_Text,Type,Media_Type,Hashtags,Tweet_Id,Tweet_Url,twt_favourites_IS_THIS_LIKE_QUESTION_MARK,Retweets,Unnamed: 10,Unnamed: 11
0,16-11-11,15:26:37,Today we express our deepest gratitude to all ...,text,photo,ThankAVet,7.970000e+17,https://twitter.com/realDonaldTrump/status/797...,127213,41112,NaN,NaN
1,16-11-11,13:33:35,Busy day planned in New York. Will soon be mak...,text,NaN,NaN,7.970000e+17,https://twitter.com/realDonaldTrump/status/797...,141527,28654,NaN,NaN
2,16-11-11,11:14:20,Love the fact that the small groups of protest...,text,NaN,NaN,7.970000e+17,https://twitter.com/realDonaldTrump/status/797...,183729,50039,NaN,NaN
3,16-11-11,2:19:44,Just had a very open and successful presidenti...,text,NaN,NaN,7.970000e+17,https://twitter.com/realDonaldTrump/status/796...,214001,67010,NaN,NaN
4,16-11-11,2:10:46,A fantastic day in D.C. Met with President Oba...,text,NaN,NaN,7.970000e+17,https://twitter.com/realDonaldTrump/status/796...,178499,36688,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
7370,15-07-16,13:10:00,I loved firing goofball atheist Penn @pennjill...,text,NaN,NaN,6.220000e+17,https://twitter.com/realDonaldTrump/status/621...,953,431,NaN,NaN
7371,15-07-16,10:18:31,I hear @pennjillette show on Broadway is terri...,text,NaN,NaN,6.220000e+17,https://twitter.com/realDonaldTrump/status/621...,1175,1086,NaN,NaN
7372,15-07-16,10:10:17,Irrelevant clown @KarlRove sweats and shakes n...,text,NaN,NaN,6.220000e+17,https://twitter.com/realDonaldTrump/status/621...,1494,930,NaN,NaN
7373,15-07-16,9:44:07,"""@HoustonWelder: Donald Trump is one of the se...",text,NaN,NaN,6.220000e+17,https://twitter.com/realDonaldTrump/status/621...,1800,1738,NaN,NaN
7374,15-07-16,0:21:25,RT @marklevinshow: Trump: Rove is a clown and ...,link,NaN,NaN,6.210000e+17,https://twitter.com/realDonaldTrump/status/621...,962,689,NaN,NaN

In [12]:
for col in donald_data_df.columns: 
    print(col)

Date
Time
Tweet_Text
Type
Media_Type
Hashtags
Tweet_Id
Tweet_Url
twt_favourites_IS_THIS_LIKE_QUESTION_MARK
Retweets
Unnamed: 10
Unnamed: 11

In [26]:
# json_file = "donald_data2.json", lines=True
# donald_json_df = pd.read_json(json_file)
donald_json_file = pd.read_json('donald_data2.json', lines=True)
donald_json_file

,created_at,id,id_str,full_text,truncated,display_text_range,entities,extended_entities,source,in_reply_to_status_id,...,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,quoted_status_id,quoted_status_id_str,quoted_status_permalink,quoted_status
0,2018-09-11 20:16:49+00:00,1039608725819088899,1039608725819088896,The safety of American people is my absolute h...,False,"[0, 185]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 1039608069599240194, 'id_str...","<a href=""http://twitter.com/download/iphone"" r...",NaN,...,7270,27341,False,False,0.0,en,NaN,NaN,NaN,NaN
1,2018-09-11 16:48:49+00:00,1039556378766069760,1039556378766069760,Small Business Optimism Soars to Highest Level...,False,"[0, 106]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",NaN,...,8520,31085,False,False,0.0,en,NaN,NaN,NaN,NaN
2,2018-09-11 15:32:28+00:00,1039537164458053633,1039537164458053632,#NeverForget #September11th \nhttps://t.co/l8W...,False,"[0, 52]","{'hashtags': [{'text': 'NeverForget', 'indices...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",NaN,...,9641,33968,False,False,0.0,und,NaN,NaN,NaN,NaN
3,2018-09-11 12:58:10+00:00,1039498334594052096,1039498334594052096,17 years since September 11th!,False,"[0, 30]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",NaN,...,17952,73372,False,False,NaN,en,NaN,NaN,NaN,NaN
4,2018-09-11 12:24:52+00:00,1039489954223542274,1039489954223542272,"Departing Washington, D.C. to attend a Flight ...",False,"[0, 136]","{'hashtags': [{'text': 'NeverForget', 'indices...","{'media': [{'id': 1039489901690056704, 'id_str...","<a href=""http://twitter.com/download/iphone"" r...",NaN,...,12541,52227,False,False,0.0,en,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2860,2017-09-06 10:53:45+00:00,905383515302264832,905383515302264832,Hurricane looks like largest ever recorded in ...,False,"[0, 59]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",NaN,...,12226,56660,False,False,NaN,en,NaN,NaN,NaN,NaN
2861,2017-09-06 10:51:52+00:00,905383039517282304,905383039517282304,"Watching Hurricane closely. My team, which has...",False,"[0, 138]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",NaN,...,20181,104511,False,False,NaN,en,NaN,NaN,NaN,NaN
2862,2017-09-06 10:47:01+00:00,905381817695526912,905381817695526912,Will be going to North Dakota today to discuss...,False,"[0, 136]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",NaN,...,16359,85389,False,False,NaN,en,NaN,NaN,NaN,NaN
2863,2017-09-06 00:38:27+00:00,905228667336499200,905228667336499200,Congress now has 6 months to legalize DACA (so...,False,"[0, 139]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",NaN,...,22484,87620,False,False,NaN,en,NaN,NaN,NaN,NaN
2864,2017-09-05 20:45:27+00:00,905170032229056512,905170032229056512,I look forward to working w/ D's + R's in Cong...,False,"[0, 140]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",NaN,...,22529,98351,False,False,NaN,en,NaN,NaN,NaN,NaN

In [17]:
for col in donald_json_file: 
    print(col)

created_at
id
id_str
full_text
truncated
display_text_range
entities
extended_entities
source
in_reply_to_status_id
in_reply_to_status_id_str
in_reply_to_user_id
in_reply_to_user_id_str
in_reply_to_screen_name
user
geo
coordinates
place
contributors
is_quote_status
retweet_count
favorite_count
favorited
retweeted
possibly_sensitive
lang
quoted_status_id
quoted_status_id_str
quoted_status_permalink
quoted_status

In [18]:
rds_connection_string = "postgres:Catpuss10!@localhost:5432/customer_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [19]:
engine.table_names()

['customer_name', 'customer_location', 'premise', 'county']